### ISSUE TITLE
Adicionar novos termos técnicos dentro do projeto conforme a descrição

### ISSUE THREAD

**Issue by morgannadev** [levxyca/diciotech#101]
Olá! Eu havia iniciado um tempo atrás algumas explicações sobre termos técnicos e acho que seria bacana trazer esses termos para dentro do diciotech.

As palavras e explicações podem ser vistas [neste repositório](https://github.com/morgannadev/dicionario), mas segue a listagem delas abaixo:

- Ambiente (local, dev, homologação e produção);
- API;
- Code Review;
- Commit;
- Deploy;
- Json;
- Pair Programming;
- Pull Request.

E, se for aceita a proposta, gostaria de pedir que atribuísse a issue a mim, para que eu possa adicionar as palavras. Obrigada!

**Comment by levxyca** [comment]
Eu que agradeço 💖
