### ISSUE TITLE
Adicionar termos Banco de Dados (termo e tag), NoSQL  e Banco Relacional

### ISSUE THREAD

**Issue by DanieleKaroline** [levxyca/diciotech#117]
Oii! Irei adicionar os termos e definições de Banco de Dados (termo e tag), NoSQL  e Banco Relacional :)

**Comment by levxyca** [comment]
Oie @DanieleKaroline! Para adicionar uma nova tag no Diciotech, temos esse passo a passo: [Adicionando uma nova tag no Diciotech](https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md#adicionando-uma-nova-tag-no-diciotech)! Como existe uma área voltada para banco de dados pode ser sim interessante adicionar essa nova tag! No mais, também pode se utilizar a tag "conceito" que já existe atualmente no projeto.

Se tiver qualquer dúvida, estou aqui :)

**Comment by levxyca** [comment]
> Oie @DanieleKaroline! Para adicionar uma nova tag no Diciotech, temos esse passo a passo: [Adicionando uma nova tag no Diciotech](https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md#adicionando-uma-nova-tag-no-diciotech)! Como existe uma área voltada para banco de dados pode ser sim interessante adicionar essa nova tag! No mais, também pode se utilizar a tag "conceito" que já existe atualmente no projeto.
> 
> Se tiver qualquer dúvida, estou aqui :)

Sobre criar a nova tag, se quiser levar para a discussão com a comunidade, também é valido!

**Comment by DanieleKaroline** [comment]
Oii, @levxyca! Eu fiz o pr com as add. Para a definição de Banco, usei as tags "Conceito" e "Banco de Dados". A tag de banco eu criei conforme o documento mesmo :)
