### ISSUE TITLE
Adicionar tag "Redes"

### ISSUE THREAD

**Issue by SystemGuuh** [levxyca/diciotech#121]
Eu queria adicionar alguns termos na área de redes, como protocólos de comunicação, TCP, UDP, HTTP, HTTPS e assim por diante. Caso não faça sentido colocar essa tag, colocaria esses termos como? conceito?

**Comment by taernsietr** [comment]
Acho que faz sentido criar uma tag de "protocolo", considerando a quantidade de coisas que teria pra colocar... mas não sei se no geral achariam redundante com conceito.

**Comment by levxyca** [comment]
@SystemGuuh Obrigada pela sugestão! Acho válido sim, pensando que existe toda uma área por trás, pensei em algo como "Infraestrutura de Rede" o que acha? A ideia das tags é ser algo super genérico e caso a pessoa usuária queira algo específico ela deve usar a barra de pesquisa.

**Comment by levxyca** [comment]
@SystemGuuh adicionado a tag "Infraestrutura de Rede" na documentação oficial do Diciotech 🚀
