### ISSUE TITLE
Adição de várias novas definições, incluindo Docker, Podman, máquinas virtuais, etc.

### ISSUE THREAD

**Issue by cosmic-zip** [levxyca/diciotech#128]
Adição de várias novas definições, incluindo Docker, Podman, máquinas virtuais, etc.
Todos os conteúdos são extraídos do meu livro de definições DEV_DEF e foram 
incluídos aqui devido à semelhança de propósitos com os projetos.

**Comment by levxyca** [comment]
PR fechada pela pessoa autora do projeto https://github.com/levxyca/diciotech/pull/127
