### ISSUE TITLE
Tentativa de add novo termo

### ISSUE THREAD

**Issue by leitoraincomum** [levxyca/diciotech#133]
Estou tentando adicionar um PR com termo novo sem sucesso.

Pode me ajudar?

**Comment by levxyca** [comment]
Oi @leitoraincomum 😊 Claro! Pode me descrever qual o problema que está ocorrendo?

**Comment by leitoraincomum** [comment]
Está dando conflito de merge mesmo sem ter linhas parecidas como se estivesse bloqueado, mas não consigo resolver.

Alguma dica?

**Comment by levxyca** [comment]
Fechando a issue aqui, caso queira retomar pode me chamar que ajudo 💙🫱🏻‍🫲🏻
