### ISSUE TITLE
Adicionar tag `Rede neural` e `Inteligência artificial`

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#146]
Com a alta dessas áreas no mundo, acho que nada mais justo que adicionar as tags `Rede neural` e `Inteligência artificial` e, consequentemente, começar a adicionar explicações sobre termos dessas áreas. Claro, sempre com a simplicidade que tem sido usada nas explicações que eu tenho visto no projeto, que acho incrível.

**Comment by levxyca** [comment]
Oie @george-gca! Primeiramente, muito obrigada pela sua sugestão! Acho a ideia super válida! Como a proposta das tags é ser algo bem abrangente, o que acha de pensarmos em um nome que possa englobar todos esses conceitos? Tem alguma sugestão?

**Comment by george-gca** [comment]
Então, esses nomes já são as versões mais abrangentes possíveis. `Inteligência artificial`, por exemplo, é uma grande área de estudo que envolve inclusive `aprendizado de máquina` [internamente](https://ai.engineering.columbia.edu/ai-vs-machine-learning/#:~:text=Artificial%20intelligence%20(AI)%20and%20machine,the%20broader%20category%20of%20AI.).

O mesmo vale pra redes neurais, que são modelos computacionais baseados no funcionamento do cérebro. O máximo que acho que pode ser feito é alterar `redes neurais` pra `redes neurais artificiais`.
