### ISSUE TITLE
Adicionar tag "Web3"

### ISSUE THREAD

**Issue by martechbm** [levxyca/diciotech#170]
Blz?? Eu pretendo adicionar alguns termos na área de **Web3**, acho que faz sentido por ser um universo imenso e novo com foco em web descentralizada. Tem muita gente curiosa em assuntos como Tecnologia Blockchain, Linguagens de Alto Nível importantes como a Solidity, Carteiras Digitais e Cripitoativos, NFTs, DeFi e mais um monte de coisas e tudo criando um novo marco no desenvolvimento web. Será que da pra rolar essa tag?

**Comment by levxyca** [comment]
@martechbm super rola sim! adicionei na documentação do Diciotech!
