### ISSUE TITLE
Detectar automaticamente tema do sistema

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#173]
### Descrição do recurso

Seria legal detectar automaticamente o tema do sistema pra aplicar no site.

### Motivação

Toda vez que eu abro o site preciso mudar o tema para o modo dark, o que não é ideal.

### Sugestão de implementação

Uma opção seria fazer algo como feito [nesse site](https://alshedivat.github.io/al-folio/), onde tem as opções `padrão do sistema`/`claro`/`escuro` usando ícones pra indicar qual a opção atual (ícones do [Tabler Icons](https://tablericons.com/)) 

![image](https://github.com/levxyca/diciotech/assets/31376482/2fa1cae0-eb59-4d43-9777-31d2a1517233)

ou como é feito no [Excalidraw](https://excalidraw.com/) que usa um ícone de tela pra indicar padrão do sistema.

![image](https://github.com/levxyca/diciotech/assets/31376482/a69d4acc-226e-4199-8514-35b4274b22ee)

**Comment by gabrielliosc** [comment]
Como já vou mexer na issue do dark mode, posso pegar essa issue também.

**Comment by levxyca** [comment]
@gabrielliosc perfeito, vou atribuir pra você 💙

**Comment by george-gca** [comment]
Acabei de ver que o projeto usa o [Phosphor icons](https://phosphoricons.com/)

https://github.com/levxyca/diciotech/blob/ab173c173408934221650aa63b44c206dc10bf85/index.html#L23

mas que eles [só são usados pro ícone de mudar o tema](https://github.com/search?q=repo%3Alevxyca%2Fdiciotech%20ph%20ph-&type=code). Acho que o ícone de usar o tema do sistema pode ser o [desktop](https://phosphoricons.com/?q=%22desktop%22&weight=%22regular%22). Caso fosse alterar para o [Tabler icons](https://tabler.io/icons) (também é licença MIT), aí poderia usar o [sun-moon](https://tabler.io/icons/icon/sun-moon) de repente.
