### ISSUE TITLE
[TERMOS DUPLICADOS]

### ISSUE THREAD

**Issue by julia-sarmento** [levxyca/diciotech#183]
### Descrição do problema

Hey, pessoal! Temos alguns conceitos duplicados na aplicação. São os termos "Pull Request" e "Branch". 
Alguém se habilita a fazer este adorável fix?  

### Como reproduzir o problema?

Onde: https://diciotech.netlify.app/
Plataformas: **Desktop e Mobile**

### Mais informações

<img width="961" alt="duplicated_terms" src="https://github.com/user-attachments/assets/8cff98bb-589e-42d8-bca7-7a18c9c8c244">
<img width="961" alt="duplicated_terms_1" src="https://github.com/user-attachments/assets/18398f31-bd42-4542-82ec-ea19a9019a6a">

**Comment by julia-sarmento** [comment]
Edit: acabei de ver que esse bug já foi aberto pelo colega @FabianoRaiser bem[ aqui](https://github.com/levxyca/diciotech/issues/178) então desconsiderem hehe

**Comment by levxyca** [comment]
@julia-sarmento agradecemos sua contribuição 💙
