### ISSUE TITLE
Atualizar como instalar o ambiente de desenvolvimento no CONTRIBUTING.md

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#195]
### Descrição do recurso

Ideia veio a partir da discussão https://github.com/levxyca/diciotech/discussions/193#discussion-7212301

Precisamos atualizar esse CONTRIBUTING.md com:

- [ ] Como executar um servidor HTTP localmente
- [ ] Adicionar SASS como opcional a depender do contexto (pois ele só será usado caso a pessoa queira mexer em algo visual do Diciotech)

### Motivação

Se uma pessoa quiser contribuir com código que não sejam novos termos, ela precisa primeiro instalar o ambiente de desenvolvimento na sua máquina para então poder fazer testes locais antes de submeter uma PR. Seria útil ter uma seção dentro do arquivo CONTRIBUTING.md ensinando como instalar as dependências necessárias.

### Sugestão de implementação

Atualizar [essa seção da documentação.](https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md#%EF%B8%8F-instalando-ambiente-de-desenvolvimento-para-contribuir)

**Comment by Elisabete-MO** [comment]
Vou fazer essa issue

**Comment by levxyca** [comment]
Resolvida na #211
