### ISSUE TITLE
Modo escuro atualmente dá um flash ao atualizar a página

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#197]
### Descrição do problema

Ao ativar o modo escuro a tela tem uma animação de transição, porém a mesma acontece ao atualizar a página, mesmo que o modo escuro já seja o atualmente selecionado. Em outras páginas que possuem suporte ao modo escuro (ex: GitHub) o modo escuro já é carregado, sem precisar antes carregar o modo claro e efetuar a transição pro escuro.

### Como reproduzir o problema?

1 - ativar o modo escuro
2 - atualizar a página (F5)

### Mais informações

![ezgif-1-97dc4d8405](https://github.com/user-attachments/assets/6582b8c9-c38d-4a5e-bbf2-d2ccdd9cda08)

**Comment by george-gca** [comment]
Talvez o @gabrielliosc consiga pegar esse também?

**Comment by gabrielliosc** [comment]
Posso pegar sim 😄
