### ISSUE TITLE
design do site

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#2]
Design para o projeto diciotech 📖

Esboço inicial:
![Image](https://user-images.githubusercontent.com/19956731/239073491-e8786e7b-1ccc-4747-a565-db4a2987fb27.jpg)

Design por @rafaeldellaquila:
![Image](https://user-images.githubusercontent.com/19956731/239074134-4b7993d0-b155-4e89-8911-45b298b4a783.png)

[Figma](https://www.figma.com/file/9yxaF2nfwvWu3CdnCZYdiq/DicioTech-%2F-Levs?type=design&node-id=0-1)

**Comment by rafaeldellaquila** [comment]
Oi, deixa que eu faço esse ok

**Comment by levxyca** [comment]
Obrigada pelo design 🥰
