### ISSUE TITLE
Ícone de favoritos não muda de cor no modo escuro

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#201]
### Descrição do problema

Imagens valem mais que mil palavras:

Modo claro

![image](https://github.com/user-attachments/assets/ec1656cd-a160-407c-8b7c-5415262d1473)

Modo escuro

![image](https://github.com/user-attachments/assets/fb7e2901-e0e2-4c76-a566-a8e552d8e286)

O ideal seria a estrela ficar com as bordas claras no modo escuro.

### Como reproduzir o problema?

Entrar em https://diciotech.netlify.app/ e mudar o tema

**Comment by inovaprog** [comment]
Olá, gostaria de trabalhar nesse bug. @levxyca

**Comment by levxyca** [comment]
@inovaprog é todo seu, manda ver 🚀

**Comment by george-gca** [comment]
Eu até tinha começado a dar uma olhada nisso, mas meu conhecimento de web é limitado haha. Eu tinha alterado a estrela por um svg, mas não consegui alterar a cor dela quando muda de tema.

**Comment by inovaprog** [comment]
@george-gca , minha ideia é exatamente fazer essa mudança mesmo. Transformar em svg e alterar a cor. Eu sou desenvolvedor backend então tambem algumas coisas são novas pra mim rsrsrrs.

**Comment by george-gca** [comment]
Inclusive vi que vai ser mais fácil do que a gente pensa. Acabei de ver que o projeto usa o [Phosphor icons](https://phosphoricons.com/), então dá pra [só usar de lá](https://phosphoricons.com/?q=%22star%22&weight=%22regular%22).

https://github.com/levxyca/diciotech/blob/ab173c173408934221650aa63b44c206dc10bf85/index.html#L23

**Comment by george-gca** [comment]
Deixo a bola contigo @inovaprog.
