### ISSUE TITLE
dúvida sobre CONTRIBUTING.md

### ISSUE THREAD

**Issue by ProgramadorVictor** [levxyca/diciotech#206]
### Descrição do problema

![tutorial](https://github.com/user-attachments/assets/2b2fa415-a5c9-4edd-8c18-e60d9b863116)

Eu queria adicionar alguns termos, estava seguindo o CONTRIBUTING.md, porém o comando que estava lá, não funcionou,  tem algum problema com o comando ou estou fazendo algo de  errado?

```
sass scss/styles.scss css/styles.css --watch
```

### Como reproduzir o problema?

1. Entre no repositório.
2. Digite o comando: sass scss/styles.scss css/styles.css --watch

**Comment by george-gca** [comment]
A documentação quanto a isso ainda vai ser atualizada na #195.

Pra adicionar termos esse passo não é necessário. Só precisa adicionar os termos em [assets/data/cards_pt-br.json](https://github.com/levxyca/diciotech/blob/main/assets/data/cards_pt-br.json), depois rodar um servidor web apontando pra pasta. Eu uso o python pra isso, só rodar o comando:

```bash
python3 -m http.server
```

dentro da pasta, daí abrir no teu navegador `localhost:8000` pra visualizar o site.

**Comment by levxyca** [comment]
Perfeito @george-gca! Thanks 🫰🏻

@ProgramadorVictor eu costuma usar essa extensão para rodar o servidor web https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by ProgramadorVictor** [comment]
Beleza, valeu 👍
