### ISSUE TITLE
conceito de ORM duplicado

### ISSUE THREAD

**Issue by euperinotti** [levxyca/diciotech#207]
### Descrição do problema

Atualmente, existem dois cards do conceito ORM com a mesma descrição e tags 

### Como reproduzir o problema?

1. Acesse o site do diciotech 
2. Filtre pela categoria "Back-end"
3. Pesquise por "ORM"

Ao fazer isso, dois cards são exibidos com o conceito de ORM

![image](https://github.com/user-attachments/assets/434b68aa-2284-4c0f-a560-6317dae2d831)

**Comment by inovaprog** [comment]
@euperinotti, @levxyca Posso contribuir com essa correção?

**Comment by levxyca** [comment]
@inovaprog manda brasa!
