### ISSUE TITLE
Cards de termos técnicos responsivos

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#21]
**Título da Issue: Cards de termos técnicos responsivos**
Atualmente os cards estão com tamanho fixo, ou seja, quando alguém adiciona um texto grande no projeto, o card quebra, gerando um problema de legibilidade.

**Exemplo:**
Notamos esse problema a partir do #20!
![image](https://github.com/levxyca/diciotech/assets/19956731/afe08d71-d373-40da-941f-f7a0b718f94f)

**Como resolver?**
A ideia é comportar esses textos de alguma forma, talvez a mais simples seja deixar o tamanho dos cards crescer de acordo com o conteúdo de dentro.

Caso queira se aventurar mais, temos essa issue #12 com uma nova proposta de UI que pode ir sendo aplicada.

**Comment by juandesenvolvedor** [comment]
Olá, consigo consertar isso, poderia atribuir essa tarefa a mim?

**Comment by juandesenvolvedor** [comment]
![Captura de tela 2023-09-16 103507](https://github.com/levxyca/diciotech/assets/95597422/ff3e52c0-a27f-4b7c-91b5-579ea802c5b3)
Fiz com que os cards tivessem um tamanho padrão, mas caso o texto seja maior que eles, que eles consigam se adaptar ao tamanho do texto.

**Comment by levxyca** [comment]
Resolvido pelo @juandesenvolvedor no PR #22
