### ISSUE TITLE
Contador de termos no dicionário

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#216]
### Descrição do recurso

Seria legal em alguma parte do site exibir quantos termos atualmente o dicionário possui.

### Motivação

Isso é uma forma legal de ver a evolução do dicionário.

### Sugestão de implementação

Talvez aparecer ao lado do subtítulo `Um dicionário tech para pessoas que querem aprender mais sobre termos técnicos dentro da tecnologia`

**Comment by levxyca** [comment]
@george-gca pô, adorei a ideia!
