### ISSUE TITLE
[TERM] Gitlab, Bitbucket, e outras plataformas de gerenciamento de código

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#230]
Como existe o termo Github, acho que é interessante adicionar outras plataformas bastante usadas como Gitlab e Bitbucket, e inclusive na explicação delas adicionar referência como plataformas similares e/ou concorrentes.

**Comment by george-gca** [comment]
@levxyca como era pra ficar o título da issue pra pedir termo novo?

**Comment by levxyca** [comment]
@george-gca ainda não temos um padrão para os títulos de issue ou PR 🤔 acredito que `add term` seja uma boa!

**Comment by george-gca** [comment]
Eu quis dizer se era pra ficar `[TERM]` mesmo, ou era pra ser o termo entre colchetes. Nesse sentido acho que só de ter a tag já ajuda bem, o que já tá sendo feito.

**Comment by levxyca** [comment]
@george-gca ah, entendi! isso sim!
