### ISSUE TITLE
Remover tag Back-end de Scrum e UML

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#238]
### Descrição do problema

Scrum deveria ter a tag `Framework` e não `Back-end`, `UML` ter por exemplo `Conceito` ou até uma nova tag `Linguagem de programação`

### Como reproduzir o problema?

Filtrar por tag `Back-end`

**Comment by inovaprog** [comment]
Posso fazer essa correção? @george-gca @levxyca
