### ISSUE TITLE
Adicionar scroll nos cards

### ISSUE THREAD

**Issue by Vespasianoo** [levxyca/diciotech#24]
Acessando o site a gente percebe que os cards não tem uma altura limitada o que deixa as coisas fora do padrão. Que tal definirmos uma altura e se o texto passar desse tamanho que definimos adicionamos um scroll no card ?

**Comment by levxyca** [comment]
@Vespasianoo acho que é uma boa solução, a ideia é evoluir os cards para algo como pensado na issue #7

**Comment by iuricode** [comment]
@Vespasianoo @levxyca acabei de fazer uma alteração nos cards no pull request #25
