### ISSUE TITLE
Sass + Dark Mode

### ISSUE THREAD

**Issue by iuricode** [levxyca/diciotech#26]
## Sugestões para o Futuro

- **Adoção do pré-processador Sass:** Sugiro considerar a conversão do código CSS atual para Sass. Isso proporcionaria diversas vantagens, facilitando a revisão dos commits e tornando as modificações no código mais organizadas, uma vez que estariam estruturadas em módulos.

- **Implementação do modo escuro (dark mode):** Uma valiosa adição ao projeto seria a inclusão do modo escuro. Dado que se trata de um site focado na experiência de leitura, não podemos deixar de oferecer aos usuários a opção de utilizar o modo escuro, que proporciona conforto visual.

**Comment by birobirobiro** [comment]
Acabei de mandar uma PR implementando o Dark Mode: https://github.com/levxyca/diciotech/pull/28

**Comment by thiagofqs** [comment]
Conforme sugerido nessa issue, acabei de fazer um PR implementando uma primeira versão da conversão de CSS para SASS: #30 

Essa pull request tem como dependência as seguintes PRs:
- #25 
- #28

**Comment by levxyca** [comment]
Para fins de organização peguei essa conversa e criei duas novas issues visando conseguir linkar as contribuições, mencionei essa issue nelas para mantermos o histórico e estarei fechando essa para continuarmos pelas novas issues criadas.

#36 e #37
