### ISSUE TITLE
[TERM] JSP - Java Server Pages

### ISSUE THREAD

**Issue by brunamotta** [levxyca/diciotech#260]
Esse foi mais um termo que esbarrei na faculdade e vim procurar aqui no dicionário mas não encontrei. :(

**Comment by brunamotta** [comment]
Espero que não seja um problema eu sugerir vários termos que esbarro por ai e não encontro aqui no dicionário @levxyca .

**Comment by levxyca** [comment]
Problema nenhum @brunamotta, é uma ótima contribuição 🫂😊

**Comment by brunodmartins** [comment]
@levxyca e @brunamotta eu posso abrir um PR! @levxyca vc me assigna a Issue?

**Comment by levxyca** [comment]
@brunodmartins perfeito, arrasou! tá contigo 🚀
