### ISSUE TITLE
Permitir instalação do diciotech como um webapp

### ISSUE THREAD

**Issue by george-gca** [levxyca/diciotech#261]
### Descrição do recurso

Permitir a [instalação](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Installing) do diciotech como um webapp, como o GitHub por exemplo.

![image](https://github.com/user-attachments/assets/b17b74cf-4b27-4b62-b8a5-2e62a066f790)

### Motivação

Isso permite rodar o diciotech como uma aplicação isolada em tela cheia. Pode ser útil pra alguns usuários.

### Sugestão de implementação

Seguindo os [padrões já definidos](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs) criando um [manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest).

**Comment by levxyca** [comment]
Boaaaaaaaaaa!
