### ISSUE TITLE
Adição da tag "DevOps"

### ISSUE THREAD

**Issue by devsnasnuvens** [levxyca/diciotech#264]
### Descrição do recurso

Olá!

Considerando que no planejamento de evolução do projeto foi colocada a inclusão de termos avançados de DevOps, eu gostaria de contribuir com o projeto com esses termos. 
Para reunir todos os termos que são relacionados a DevOps (inclusive já vi que tem integração contínua, entrega contínua, etc), proponho a criação de uma nova tag.

**Comment by levxyca** [comment]
oie @devsnasnuvens! obrigada pela sua contribuição! acho super válido termos uma tag específica para devops 🚀

adicionado em https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md#adicionando-uma-nova-tag-no-diciotech

**Comment by devsnasnuvens** [comment]
Oi @levxyca 
Obrigada por add!

Vou incluir alguns termos e vou abrir um PR, ok?

**Comment by levxyca** [comment]
@devsnasnuvens perfeito 🤩 só não esquece de antes abrir as issues relacionadas a esses termos, por favor 💙
