### ISSUE TITLE
Adicionar selo Hacktoberfest ao projeto

### ISSUE THREAD

**Issue by Ryrden** [levxyca/diciotech#27]
Em menos de 24h vai abrir um dos maiores eventos de Open Source aqui do Github e acho bacana que esse projeto tenha a tag hacktoberfest para maior interação da comunidade :) 

para mais informações: https://hacktoberfest.com/

**Comment by birobirobiro** [comment]
@levxyca Já começou o evento, seria legal adicionar antes de aceitar as PRs que estão em aberto

https://github.com/levxyca/diciotech/pulls

**Comment by levxyca** [comment]
Boa tarde pessoal, com certeza vamos participar da Hacktoberfest, amanhã a noite é o horário que eu tiro para mexer no projeto, vou fazer isso, além de revisar as PR's e atualizar tudo 🥳 @Ryrden @birobirobiro

**Comment by Ryrden** [comment]
perfeito @levxyca, durante o evento irei tentar contribuir para o projeto, agora é a hora certa para criar issues do que o projeto precisa :)

**Comment by levxyca** [comment]
Adicionado o selo de participação na Hacktoberfest 🚀
