### ISSUE TITLE
Filtro

### ISSUE THREAD

**Issue by iuricode** [levxyca/diciotech#31]
## Sugestões para o Futuro (parte 2)

Considerando que a comunidade já discutiu os dois tópicos mencionados na Issue #26, gostaria de apresentar uma nova sugestão para o futuro:

- Implementação de um filtro: Seria muito útil contar com um filtro que permitisse aos usuários buscar especificamente por cards que sejam de seu interesse. Isso significa ter a capacidade de filtrar por categoria, como "CSS", para encontrar de maneira mais eficiente conteúdo relacionado a esse tópico.

Forte abraço!

**Comment by gabrielviol** [comment]
Pensando nesse filtro, seria interessante que os objetos dentro do arquivo "cards_pt-br.json" tivessem mais uma propriedade, um array de tags, para conseguir filtrar.

```json
{
            "title": "Ternário",
            "description": "Expressão condicional.",
            "content": {
                "code": "Expressão ? Verdadeiro : Falso;"
            }
            "tag":["javascript",   "PHP", "Ruby"]
 }
```

**Comment by armindomatheus** [comment]
Inclui na PR #38  essa nova sugestão de filtros para os cards. Dessa forma ficou mais fácil a busca dos termos!
Acredito que com essa estrutura futuramente possa ser implementado um metodo de filtro mais complexo onde poderão ser selecionado varios filtros de uma vez do que apenas um como é agora

**Comment by Ryrden** [comment]
> Pensando nesse filtro, seria interessante que os objetos dentro do arquivo "cards_pt-br.json" tivessem mais uma propriedade, um array de tags, para conseguir filtrar.
> 
> ```json
> {
>             "title": "Ternário",
>             "description": "Expressão condicional.",
>             "content": {
>                 "code": "Expressão ? Verdadeiro : Falso;"
>             }
>             "tag":["javascript",   "PHP", "Ruby"]
>  }
> ```

Quanto a propriedade da tag, é imprescindível a existência deste campo mas para uma manipulação adequada seria interessante um banco de dados para manter o projeto, já há algum planejamento para isso? @levxyca

**Comment by levxyca** [comment]
> > Pensando nesse filtro, seria interessante que os objetos dentro do arquivo "cards_pt-br.json" tivessem mais uma propriedade, um array de tags, para conseguir filtrar.
> > ```json
> > {
> >             "title": "Ternário",
> >             "description": "Expressão condicional.",
> >             "content": {
> >                 "code": "Expressão ? Verdadeiro : Falso;"
> >             }
> >             "tag":["javascript",   "PHP", "Ruby"]
> >  }
> > ```
> 
> Quanto a propriedade da tag, é imprescindível a existência deste campo mas para uma manipulação adequada seria interessante um banco de dados para manter o projeto, já há algum planejamento para isso? @levxyca

Ainda não temos um planejamento para isso. Acredito que nesse momento, com o crescimento do projeto, seja importante mapear e ordenar por prioridade os próximos passos do projeto.

**Comment by levxyca** [comment]
Criei uma discussão para entermos melhor os próximos passos em conjunto com a comunidade: https://github.com/levxyca/diciotech/discussions/44
