### ISSUE TITLE
Implementar Dark Mode

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#36]
Conforme conversado na issue #26 em uma sugestão do @iuricode, a ideia é implementar um modo escuro (dark mode) no diciotech para melhorar a experiência de leitura.

> **Implementação do modo escuro (dark mode):** Uma valiosa adição ao projeto seria a inclusão do modo escuro. Dado que se trata de um site focado na experiência de leitura, não podemos deixar de oferecer aos usuários a opção de utilizar o modo escuro, que proporciona conforto visual.

**Comment by birobirobiro** [comment]
Conflitos resolvidos! @levxyca ✅

**Comment by birobirobiro** [comment]
@levxyca A PR https://github.com/levxyca/diciotech/pull/30 já tinha pego meu dark mode como base e fez alguns ajustes que você citou, pode fechar a https://github.com/levxyca/diciotech/pull/28. Depois que a dele for aprovada eu faço as atualizações necessárias em cima. E se quiser fechar essa issue aqui também 😃

**Comment by levxyca** [comment]
@birobirobiro fechou então :)
