### ISSUE TITLE
Converter CSS para SASS

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#37]
Conforme conversado na issue #26 em uma sugestão do @iuricode, a ideia é converter o código CSS atual para SASS, proporcionando diversas vantagens e tornando as modificações de estilização um pouco mais organizadas.

> **Adoção do pré-processador Sass:** Sugiro considerar a conversão do código CSS atual para Sass. Isso proporcionaria diversas vantagens, facilitando a revisão dos commits e tornando as modificações no código mais organizadas, uma vez que estariam estruturadas em módulos.

**Comment by thiagofqs** [comment]
Perfeito! Assim dá para fazer uma organização mais modular, usar e abusar de variáveis e mixins, usar aninhamento de regras e todo o resto que o SASS oferece 🚀
