### ISSUE TITLE
Adicionar opção de favoritar um card

### ISSUE THREAD

**Issue by thiagofqs** [levxyca/diciotech#41]
Uma ideia muito interessante seria a possibilidade de marcar cards como favoritos, armazenando de forma local no navegador. Assim, os usuários podem desfrutar de uma maior organização e até mesmo ordenar e filtrar os resultados de acordo com os cards favoritados.

## Objetivo
Adicionar uma opção de favoritar um card, armazenando os dados de forma local, com `localStorage` ou `sessionStorage`.

## Tarefas
- [ ] Incluir opção de favoritar um card, de forma individual;
- [ ] Implementar armazenamento local (localStorageou sessionStorage) para manter informações de favoritos para os usuários;
- [ ] Implementar um consentimento de cookies para se adequar a **LGPD**.

## Referências
Esta issue pode ser relacionada e complementada com as seguinte issues:
- #31;
- #7.

**Comment by KastroWalker** [comment]
Tenho interesse em adicionar essa funcionalidade. Poderiam atribuir ela pra mim? Faço nesse fim de semana.

cc: @levxyca @thiagofqs

**Comment by levxyca** [comment]
Adorei a ideia @thiagofqs 🥳 já atribui a você @KastroWalker ✨

**Comment by birobirobiro** [comment]
> Tenho interesse em adicionar essa funcionalidade. Poderiam atribuir ela pra mim? Faço nesse fim de semana.
> 
> cc: @levxyca @thiagofqs

@KastroWalker Talvez essa lib te ajude a implementar a parte ali dos cookies, ela é bem personalizável 😃

https://orestbida.com/demo-projects/cookieconsent/

**Comment by KastroWalker** [comment]
Opa @thiagofqs.
Eu adicionei a funcionalidade aqui, o que está faltando era justamente isso, de saber como adicionar na UI a opção de favoritar. Inicialmente eu pensei em ser um icone de uma estrela.
Eu não manjo muito de UI/UX então não sei se isso é a melhor opção, fiquem a vontade para me indicarem de como seria uma boa forma de fazer.

**Comment by levxyca** [comment]
> Opa @thiagofqs. Eu adicionei a funcionalidade aqui, o que está faltando era justamente isso, de saber como adicionar na UI a opção de favoritar. Inicialmente eu pensei em ser um icone de uma estrela. Eu não manjo muito de UI/UX então não sei se isso é a melhor opção, fiquem a vontade para me indicarem de como seria uma boa forma de fazer.

@kvnol tem alguma sugestão? até pensando na UI 2.0

**Comment by levxyca** [comment]
@KastroWalker acho que dá pra adicionar um ícone de estrelinha em algum dos cantinhos do card e através do feedback da comunidade, podemos modificar depois se necessário esse posicionamento!
