### ISSUE TITLE
Adicionando uma largura máxima para o último card da lista.

### ISSUE THREAD

**Issue by davi-sant** [levxyca/diciotech#53]
Neste pull request #52 estou adicionando uma largura máxima para o último card da lista, onde o mesmo por não ter uma largura máxima esticava até o tamanho máximo do elemento pai, trazendo um pouco inconsistência ao layout.

### Após plicar as mudanças sugeridas, o último elemento manterá o padrão de design. 

![Captura de tela de 2023-09-29 14-30-47](https://github.com/levxyca/diciotech/assets/97963191/a9fc796a-2c08-4f65-9579-a65de803dbb8)

**Comment by levxyca** [comment]
Muito obrigada pela sua contribuição 🤩 criei uma [enquete](https://github.com/levxyca/diciotech/discussions/64) para a comunidade votar sobre essa mudança, como essa questão de ter o último card preenchendo todo o grid foi uma proposta recentemente, gostaria de entender das pessoas que utilizam o site, o que elas preferem. Se quiser adicionar algum comentário lá também ou votar fique a vontade :)

**Comment by levxyca** [comment]
@davi-sant a comunidade aprovou a mudança 🫰🏻 só para deixar transparente aqui!

<img width="451" alt="image" src="https://github.com/levxyca/diciotech/assets/19956731/ea4e75c2-2f3a-4665-8cdd-e15ca9a7e9a8">
