### ISSUE TITLE
Adição de termos relacionados a programação baixo nível ou médio

### ISSUE THREAD

**Issue by Ryrden** [levxyca/diciotech#66]
Criei alguns novos termos, tive certa dificuldade na definição das tags, claro que, como ainda há poucas palavras cadastradas foi fácil encontrar quais já existem e assim reaproveitar mas fica de sugestão futura a implementação de um sistema de cadastro de tags + sugestão de tags

**Comment by levxyca** [comment]
@Ryrden super válida a sua sugestão, visando tentar melhorar isso de forma mais rápida criei essa issue #70 ✨ acredito que isso já vá ajudar um pouco a melhorar isso, também tenho percebido que várias pessoas tem tido dificuldades com as tags!

Podemos pensar em como implementar futuramente esse sistema de cadastro + sugestão de tags.
