### ISSUE TITLE
Como usuário gostaria de clicar no card de cada termo e abrir um modal com informações detalhadas

### ISSUE THREAD

**Issue by caduamorimm-dev** [levxyca/diciotech#7]
- Caso seja algo técnico: no modal exibe um exemplo de implementação.
- Assuntos mais teóricos: detalhes em texto ou links de artigos com material complementar de estudos.

**Comment by kvnol** [comment]
@caduamorimm-dev @levxyca desenhei o wireframe do protótipo, imagino que poderíamos seguir nessa linha com modal por enquanto, buscando as informações de um json simples. Pode ser visto no Figma: https://www.figma.com/proto/zzIpvaXhueCT5w9AFJjc7J/App?page-id=0%3A1&type=design&node-id=1-14&viewport=596%2C341%2C0.74&t=m7HxJOaLtRuwHaUi-1&scaling=scale-down&starting-point-node-id=1%3A14&mode=design

**Comment by motive-mobi** [comment]
Um agrupamento por categoria (linguagem de programação a que se refere o card), via tags dentro dos cards seria interessante mais a frente?

**Comment by levxyca** [comment]
@motive-mobi que acredito que seja interessante sim, ajudaria muito a organizar e facilitar para pessoas que queiram ver todos os cards de um assunto específico, só penso que seria legal tomar um cuidado ao pensar nessa feature para não deixar o site com muitas coisas visuais que atrapalhem o foco da leitura do conteúdo, saca?

**Comment by motive-mobi** [comment]
sim, com certeza... um badge (que já pode ser um filtro) num cantinho do card... pensei em algo mais ou menos assim.

**Comment by levxyca** [comment]
@motive-mobi acho bem legal sim!

**Comment by thiagofqs** [comment]
> @levxyca sim, com certeza... um badge (que já pode ser um filtro) num cantinho do card... pensei em algo mais ou menos assim.

Nesse caso, os badges podem complementar a issue #31 e a PR #38, que abordam justamente essa questão dos filtros dos cards por categoria. Ótima ideia!

**Comment by levxyca** [comment]
Vou fechar essa issue pois as coisas mencionada aqui já foram ou estão em desenvolvimento, sobre as badges, podemos levar pros `discussions` para enteder melhor como fazer, o que acham? @motive-mobi @thiagofqs
