### ISSUE TITLE
Dark mode refatorado

### ISSUE THREAD

**Issue by thiagofqs** [levxyca/diciotech#80]
No PR #79, refatorei o código JavaScript e CSS do dark mode e separei toda a estilização do mesmo em um arquivo SASS diferente, para uma maior organização do projeto.

Além disso, adicionei novas tonalidades da cor primária (#6e6197) no `_variabels.sass` e removi a tag duplicada "Back-End" que estava presente no termo _Python_. Com relação as tags, deve ser tomado mais cuidado para que essas duplicações não venham a ocorrer com frequência, pois essas tags são case sensitivity.

**Comment by levxyca** [comment]
@thiagofqs bacana demais! sobre isso, acho legal adicionar na documentação também né? eu não estava me atentando a questão do case sentitivity!

**Comment by thiagofqs** [comment]
> @thiagofqs bacana demais! sobre isso, acho legal adicionar na documentação também né? eu não estava me atentando a questão do case sentitivity!

Concordo, @levxyca! Acho que deve ter uma parte explicando sobre o uso adequado das tags (sempre no singular) e vinculando a um novo termo apenas as disponíveis (lista na issue #62). Caso seja necessário adicionar mais uma tag, que seja necessário abrir uma issue sugerindo a nova tag e adicionando na documentação, para aí sim poder usa-las em um PR.

**Comment by levxyca** [comment]
Show demais @thiagofqs! Consegue criar uma issue com esses pontos para me dar um help? 🥹

**Comment by thiagofqs** [comment]
> Show demais @thiagofqs! Consegue criar uma issue com esses pontos para me dar um help? 🥹

Com toda a certeza, @levxyca! Além da issue, quer que eu também abra um PR ou preferes que eu faça apenas a issue com esses pontos?

**Comment by levxyca** [comment]
@thiagofqs fique a vontade, se tiver com tempo disponível e já quiser abrir o PR também é show!

**Comment by thiagofqs** [comment]
> @thiagofqs fique a vontade, se tiver com tempo disponível e já quiser abrir o PR também é show!

Beleza, @levxyca! Como o PR #71 já acrescenta alguns dos pontos, que citei, na documentação, quando o mesmo for mergeado eu faço uma issue e abro um novo PR para complementar 😉✌️.

**Comment by levxyca** [comment]
@thiagofqs show de bola!

**Comment by thiagofqs** [comment]
> @thiagofqs show de bola!

Prontinho, @levxyca, descrevi tudo na issue #91! Se puder dar uma conferida lá depois e dar o seu feedback pessoal, agradeço muito. Se estiver de acordo, pode atribuir a issue a mim que abro um PR.
