### ISSUE TITLE
Bug na exibição dos cards na tela principal. 

### ISSUE THREAD

**Issue by davi-sant** [levxyca/diciotech#82]
No arquivo .jon tinha uma linha que contia uma vírgula indesejada, foi feita a remoção e o erro foi corrigido, apesar do erro ser simples a página no atual momento está sem ultilidade, pois nenhum card é exibido no momento. 

Correção na PR: #81

@levxyca

**Comment by levxyca** [comment]
@davi-sant obrigada por notar o problema e corrigir, acredito que agora está tudo ok, acabaram mandando um PR antes do seu corrigindo esse problema!
