### ISSUE TITLE
Inserir dados de fonte dos conceitos apresentados

### ISSUE THREAD

**Issue by tamirfaria** [levxyca/diciotech#86]
Seria interessante apresentar a fonte dos conceitos para que isso passe mais credibilidade e sirva de base para consulta.
Nesse caso seria adicionada a propriedade "font" que engloba "autor" e "source" na classe dos cards 👇.
`

    {
      "title": "Abstração",
      "description": "Abstração é uma simplificação de ponto(s) específicos de algum sistema ou comportamento estamos tentando entender. Na programação, usamos abstrações o tempo todo. Isso significa que não precisamos entender todos os detalhes técnicos profundos para escrever código - como o funcionamento interno de um computador. Em vez disso, podemos usar ideias mais simples para criar nossos programas.",
      "tags": ["Conceito"],
      "font": {
         "autor": "Martin Fowler"
         "source": "Código Limpo"
         }
    }
    
 `
 
 @levxyca, se possível atribuir a issue à mim!

**Comment by levxyca** [comment]
Acho válido madurarmos melhor essa ideia, talvez algo como "referências" e não fonte. A ideia do diciotech não é ser um copia e cola de termos e sim pegar explicações complexas e explicar elas de uma forma simples e didática, por isso, acredito que o termo de "font" não se aplique, visto que não seria um texto de algum autor em específico.

**Comment by tamirfaria** [comment]
Faz sentido @levxyca !
