### ISSUE TITLE
Adicionando templates de issue

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#92]
Para tornar a experiência de contribuição mais eficaz, disponibilizaremos modelos de issues que as pessoas contribuidoras possam utilizar. Haverá três tipos distintos de modelos:

- [ ] Template de issue para reportar bugs
- [ ] Template de issue para solicitar uma nova funcionalidade
- [ ] Template de issue para adicionar um novo termo ao dicionário do tecnologia (diciotech)

**Comment by andrepg** [comment]
@levxyca olá, novamente. Fiz uma cópia do repositório e estou trabalhando em alguns modelos (inicialmente estes do issue). Se quiser pode me colocar como responsável aqui e vamos evoluindo/conversando conforme os criamos.

Os modelos iniciais em desenvolvimento podem ser vistos aqui. E, claro, podemos melhorá-los a qualquer momento, inclusive enquanto escrevo. Basta dar um ping aqui e discutimos as modificações. 

Uma sugestão que eu gostaria de fazer é vincular issues de novos termos a alguma discussão, na qual podemos avaliar a viabilidade de inclusão. Não seria obrigatório, mas auxiliaria a não abrir muitos deles em troca de uma maior discussão com a comunidade.
