### ISSUE TITLE
Adicionando template de pull request

### ISSUE THREAD

**Issue by levxyca** [levxyca/diciotech#93]
Visando facilitar e manter um padrão nas contribuições, vamos ter um modelo de pull request para as pessoas contribuidoras se baseando no artigo do github que explica como [Criar modelos de pull request no repositório](https://docs.github.com/pt/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).

O que um `pull request` precisar ter?

- [ ] Título do PR que seja sucinto e legível
- [ ] Uma descrição das alterações propostas na pull request
- [ ] Uma [referência a issue relacionada](https://docs.github.com/pt/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#referencing-issues-and-pull-requests) no repositório.

**Comment by andrepg** [comment]
@levxyca o modelo de PR é criado da mesma forma que os outros ([conforme a DOC](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)). Aqui valem algumas questões: 

1. Vamos tipificar os PRs? (bug, melhoria, termos, etc.)
2. Os tipos, se existentes, diferirão em conteúdo? 

Pergunto porque, dependendo da discussão, podemos criar um ou mais modelos para utilização. Acredito que, pelo bem da simplicidade, podemos começar com um modelo apenas. Se for o caso, pode atribuir para mim e crio o arquivo e PR.

**Comment by levxyca** [comment]
@andrepg concordo contigo, podemos começar com um modelo e ir evoluindo conforme necessidade. É até bom termos um mobelo de inicio para facilitar ensinar a Comunidade á usar corretamente, temos muitos PR's sem título ou descrição, dessa forma temos um ótimo ponto de partida e podemos ir evoluindo 🚀 Vou atribuir para você então!

**Comment by andrepg** [comment]
Olá @levxyca, desculpe o delay para resolução, foram (e estão sendo) semanas intensas. 

Abri o PR #177  (em rascunho) para seguirmos uma discussão melhor aqui a partir do que temos de material. Quando tiver um retorno pode me pingar aqui, passo boa parte do meu tempo diário no GitHub ⌨️

**Comment by levxyca** [comment]
@andrepg acabei de revisar aqui, adicionei algumas sugestões de alterações no texto, veja o que acha 🫰🏻 Gostaria de agradecer pela sua contribuição também!
