### ISSUE TITLE
Adicionar mensagem de erro para resultados não encontrados

### ISSUE THREAD

**Issue by natanael-silv** [levxyca/diciotech#96]
Se nenhum resultado for encontrado, é um boa prática de ux retornar um mensagem informando o usuário.

**Comment by levxyca** [comment]
@natanael-silv super importante! não sei se ficaria muito poluído, mas poderia até ter alguma mensagem engajando a pessoa a contribuir para o projeto adicionando aquele termo que ela não encontrou!

**Comment by levxyca** [comment]
Fechada com o PR #69! (Closes #69)
